# Generated by Django 5.2.8 on 2026-01-06 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=100)),
                ('teacher_phone', models.CharField(max_length=100)),
                ('teacher_email', models.EmailField(max_length=100)),
                ('teacher_id', models.CharField(max_length=50)),
                ('teacher_image', models.ImageField(upload_to='teacher/')),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100)),
                ('joining_date', models.DateField()),
                ('teacher_class', models.CharField(max_length=50)),
                ('teacher_subject', models.CharField(max_length=40)),
                ('section', models.CharField(max_length=60)),
                ('address', models.TextField()),
                ('user_name', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
            ],
        ),
    ]
