# Generated by Django 5.2.8 on 2026-01-06 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='teacher_experience',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_qualifications',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
