# Generated by Django 5.2.8 on 2026-01-07 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_alter_teacher_teacher_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='password',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='zip_code',
        ),
    ]
