# Generated by Django 5.2.8 on 2026-01-08 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_remove_teacher_password_remove_teacher_user_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_image',
            field=models.ImageField(null=True, upload_to='teacher/'),
        ),
    ]
