# Generated by Django 5.2.8 on 2025-12-29 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='present_address',
            field=models.TextField(blank=True),
        ),
    ]
