# Generated by Django 5.2.8 on 2025-12-29 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_parent_present_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='present_address',
            field=models.TextField(null=True),
        ),
    ]
