# Generated by Django 5.2.8 on 2025-12-29 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_parent_present_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='permanent_address',
            field=models.TextField(null=True),
        ),
    ]
