# Generated by Django 5.2.8 on 2025-12-29 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_parent_permanent_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='permanent_address',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parent',
            name='present_address',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
