# Generated by Django 5.2.8 on 2025-12-29 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_parent_permanent_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Parent',
            new_name='parent',
        ),
    ]
