# Generated by Django 5.2.8 on 2025-12-29 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_rename_parent_student_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='permanent_address',
            field=models.TextField(null=True),
        ),
    ]
