# Generated by Django 5.2.8 on 2026-01-27 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departments',
            old_name='head_of_deparment',
            new_name='head_of_department',
        ),
    ]
