# Generated by Django 5.2.8 on 2026-01-27 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_rename_head_of_deparment_departments_head_of_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='no_of_students',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
